import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";

const banner = `/*
${fs.readFileSync("LICENSE", "utf8")}
Bundled PDF.js license:
${fs.readFileSync("THIRD-PARTY-LICENSES.txt", "utf8")}
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Embeds the worker in main.js and concatenates the pdf.js viewer CSS
// (text layer styles) with our own styles into Obsidian's expected styles.css.
const assetPlugin = {
	name: "paper-reader-assets",
	setup(build) {
		build.onEnd(() => {
			const viewerCss = fs.readFileSync(
				"node_modules/pdfjs-dist/legacy/web/pdf_viewer.css",
				"utf8"
			);
			const customCss = fs.existsSync("src/styles.css")
				? fs.readFileSync("src/styles.css", "utf8")
				: "";
			fs.writeFileSync("styles.css", viewerCss + "\n" + customCss);
		});
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	define: { __PDF_WORKER_SOURCE__: JSON.stringify(fs.readFileSync("node_modules/pdfjs-dist/legacy/build/pdf.worker.min.mjs", "utf8")) },
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [assetPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
